server :
	g++ -o server tcpserver.cpp -lmymuduo -lpthread -g
client :
	g++ -o client tcpclient.cpp -lmymuduo -lpthread -g
timer :
	g++ -o timer timerQueueTest.cpp -lmymuduo -lpthread -g

cc :
	rm -f client
cs :
	rm -f server
ct :
	rm -f timer